---
title: "publishing_class_markdown"
author: "Hugo Labat"
date: "`r Sys.Date()`"
output: html_document
---
## Code

Below, we are setting up the required libraries to perform the project.

```{r setup,warning=FALSE,message=FALSE}
library(tidyverse)
library(here)
```


And then we import the data, separate it into useful columns, and plotting the data.

```{r data important and separating data,warnig=FALSE,message=FALSE}
#importing data
df <- read.csv(here("data","per_ppt_step_mass_per_region.csv"))

#we are separating the trial number from the trial column
df <- df %>% mutate(trial_num=as.numeric(str_sub(trials,6,7))) %>% #making sure the data is numeric
  subset(select=-c(trials)) #getting rid of trials column, now that it is useless

#plotting data
p <- ggplot(df,aes(x=trial_num,y=mean,color=regions))
p+geom_jitter(height=0,width=0.1,alpha=0.3)+
  geom_smooth(formula=y~x,method=lm)+
  labs(title="Step Mass per Region per Trial")+
  xlab("Trial Number")+
  ylab("Mean Data")

#saves figure into output folder
ggsave(here("output","figs","foot_use_data_plot.png"))
```

## Summary
All done!